[mgr]
show_hidden = false
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_symlink = true

[preview]
tab_size = 2
max_width = 1000
max_height = 1000
