#!/usr/bin/env bash

# Setup script for new users to configure their username and settings

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"

echo "🚀 NixOS Dotfiles User Setup"
echo "============================="
echo ""

# Check if user.nix already exists
USER_CONFIG="$DOTFILES_DIR/hosts/framework-nixos/user.nix"
if [ -f "$USER_CONFIG" ]; then
    echo "⚠️  User configuration already exists at: $USER_CONFIG"
    read -p "Do you want to reconfigure? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
fi

# Gather user information
echo "Please provide your information:"
echo ""

read -p "Username: " USERNAME
read -p "Full Name: " FULL_NAME
read -p "Email: " EMAIL

echo ""
echo "SSH Server Aliases (optional - press Enter to skip):"
echo "Format: alias=user@host"
echo ""

declare -A SSH_ALIASES

while true; do
    read -p "Alias name (or press Enter to finish): " ALIAS_NAME
    if [ -z "$ALIAS_NAME" ]; then
        break
    fi
    read -p "SSH target (e.g., user@server.com): " SSH_TARGET
    if [ -n "$SSH_TARGET" ]; then
        SSH_ALIASES[$ALIAS_NAME]=$SSH_TARGET
    fi
done

# Generate user.nix file
echo ""
echo "📝 Generating user configuration..."

cat > "$USER_CONFIG" << EOF
# User-specific configuration variables
# Generated by setup-user.sh on $(date)

{
  # Primary user settings
  username = "$USERNAME";
  fullName = "$FULL_NAME";
  email = "$EMAIL";
  
  # SSH server aliases (optional)
  sshAliases = {
EOF

# Add SSH aliases
for alias in "${!SSH_ALIASES[@]}"; do
    echo "    $alias = \"${SSH_ALIASES[$alias]}\";" >> "$USER_CONFIG"
done

cat >> "$USER_CONFIG" << 'EOF'
  };
}
EOF

echo "✅ User configuration created at: $USER_CONFIG"
echo ""

# Update flake.nix to use the new username
echo "📝 Updating flake.nix with your username..."

# This is a simplified approach - in a real scenario, you might want to
# make flake.nix more dynamic or use a template system
sed -i "s/fschulz@framework-nixos/$USERNAME@framework-nixos/g" "$DOTFILES_DIR/flake.nix"
sed -i "s/users\.fschulz/users.$USERNAME/g" "$DOTFILES_DIR/flake.nix"

echo "✅ Configuration files updated!"
echo ""
echo "🎯 Next steps:"
echo "1. Review the generated configuration: $USER_CONFIG"
echo "2. Rebuild your system: cd $DOTFILES_DIR && ./rebuild.sh"
echo "3. If using standalone home-manager, update home-manager/flake.nix as well"
echo ""
echo "💡 Tip: You can manually edit $USER_CONFIG to add more SSH aliases later"